Type Hint, Minor changes and more tests
lipht/mvc pull request #2
Opened 2019-07-17 19:40 UTC by tarcisiozf

* annotate methods to have type hinting
* update lipht core version
* add polyfill for getallheaders cuz it's exclusive to apache
* fix tests with relative path
* require json extension
* create header abstraction for better testing
* test routes with headers
* test getallheaders
* test cors middleware

2019-07-18 14:59 UTC, SparK-Cruz requested changes
One little detail and we are all set

2019-07-18 14:59 UTC, SparK-Cruz commented on src/Controller.php
>      private function throwOrNot($exception, $throw = true)
Nice! Can we add the language hint too? `Throwable $exception`

2019-07-18 16:26 UTC, tarcisiozf commented on src/Controller.php
>      private function throwOrNot($exception, $throw = true)
sure

2019-08-02 21:58 UTC, SparK-Cruz approved these changes

2019-08-02 21:59 UTC, merged